### PR TITLE
Fixed space between search bar and filters in home page 

### LINKED ISSUE #794: The space between search bar and filters in home page should be larger
On the home page, the space between the search bar and **I want something I can** filters should be `64 px` for desktop resolution.

### Current implementation
Screen Shot 2020-03-24 at 16 47 23

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #794 

[Short description explaining the high-level reason for the pull request]

[If this Pull Request contains any UI changes, provide an image or GIF displaying the changes]

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

File: src/components/HomeLicenseFilter.vue [hunk 1]
```diff
@@ -40,7 +40,7 @@ export default {
 
 <style lang="scss" scoped>
 .home-license-filter {
-  margin-top: 0.5em;
+  margin-top: 1.5em;
```
Comment (brenoferreira) [inline src/components/HomeLicenseFilter.vue]: You should use the spacing margin classes in Vocabulary https://cc-vocabulary.netlify.com/?path=/docs/tokens-spacing--figma.

This margin doesn't add to 64px and it should be on desktop only. Mobile margin should be lower because it can cut off on smaller screens

**Comment by abhisheknaiidu** [comment]
@brenoferreira I added 40px of spacing, because there's already 24px taken by "All our content is under Creative Commons licenses. Learn more about CC licenses." Div 

So, now the space between the search bar and I want something I can filter is 64 px for desktop resolution.
