### PR TITLE
Fix space parameter between main CTA and feedback sentence

### LINKED ISSUE #952: Incorrect spacing between main CTA and sentence to form
## Describe the bug
The space between the CTA and the sentence that sends to feedback form is not correct.

## Expected behavior
The space parameter should be 8px, as indicates the [Figma mockup (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=9358%2C5775%2C1.702396035194397).

## Screenshots
Screen Shot 2020-05-14 at 12 09 24

### PR DESCRIPTION
**Pull request by ariessa**
## Fixes

Fixes #952 by @panchovm 

## Description
Added class margin-horizontal-small to fix the space between the CTA and the sentence that sends to feedback form.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository.
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/ImageDetails/PhotoDetails.vue [hunk 1]
```diff
@@ -84,7 +84,7 @@
           :href="image.foreign_landing_url"
           target="_blank"
           rel="noopener"
-          class="button is-success margin-vertical-normal"
+          class="button is-success margin-vertical-normal margin-horizontal-small"
```
Comment (brenoferreira) [inline src/components/ImageDetails/PhotoDetails.vue:87]: The issue says the margin is between the button and the reuse survey component, so a vertical margin. I think you should change this to `margin-bottom-small` and remove the horizontal margins

Comment (ariessa) [reply src/components/ImageDetails/PhotoDetails.vue]: Done
