### PR TITLE
Change icons to full opacity and add space between image name and "by"

### LINKED ISSUE #400: Lower opacity on license icons in the HTML code of image attribution and also no space between image name and "by" in rendered attribution.
**Describe the bug**
The HTML code for image attribution that the user can copy has a permanent `opacity:.7` in license icons style.
Also, there is no space between "image title" and the rest of the attribution sentence in the HTML code.
Please check the screenshots below. 

**To Reproduce**
1. Go to https://search.creativecommons.org/photos/6063b102-9445-47e5-b3a3-007d930dd4cd
2. Copy attribution HTML code.
3. Check on any online HTML editor.

**Expected behavior**
Aesthetically full opacity would look better. 

**Screenshots**

imageedit_1_8376553434

_rendered HTML_
Screenshot from 2019-06-13 11-18-14

**Desktop (please complete the following information):**
 - Browser: chrome

### PR DESCRIPTION
**Pull request by krysal**
Fixes #400

First pull request 🎉

View sample:

Captura de pantalla de 2019-10-07 14-28-32

---
<details>
<summary>Developer Certificate of Origin Version 1.1</summary>

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
</details>

### CODE REVIEW

File: src/utils/attributionHtml.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ function attributionHtml(image, ccLicenseURL, fullLicenseName) {
     ).join('');
   }
 
-  const licenseImgLink = `<a href="${ccLicenseURL}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;opacity: .7;margin-top: 2px;margin-left: 3px;height: 22px !important;">${licenseIcons}</a>`;
+  const licenseImgLink = `<a href="${ccLicenseURL}" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;opacity: 1.0;margin-top: 2px;margin-left: 3px;height: 22px !important;">${licenseIcons}</a>`;
```
Comment (brenoferreira) [inline src/utils/attributionHtml.js]: Instead of hard-coding a `opacity: 1.0`, it's better to just remove the `opacity` style. People using this on their websites might have their own opacity value on their CSS, and this will override it

**Comment by krysal** [comment]
I removed the opacity @brenoferreira
