### PR TITLE
Dismiss keyboard after search form submit on mobile

### LINKED ISSUE #532: Dismiss keyboard after search form submit on mobile
On iOS, when the user types a search query and hits the search button on the home page, once the results page loads, the iOS keyboard is still visible, taking a lot of screen space and making the actual images not visible. We should dismiss the keyboard on the form submit event.

**To Reproduce**
1. Go to CC Search home page
2. Type in a search query term
3. Hit the search button or hit "Enter" on the keyboard
4. The results page should be visible along with the iOS keyboard

**Expected behavior**
The keyboard should be dismissed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 13
 - Browser Safari

**Additional context**
Not sure if the same thing reproduces on Android and Chrome.

### PR DESCRIPTION
**Pull request by krysal**
Fixes #532

Tested on Android with Chrome browser.

---
<details>
<summary>Developer Certificate of Origin Version 1.1</summary>

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
</details>

### CODE REVIEW

File: src/components/SearchGridFormOriginal.vue [hunk 1]
```diff
@@ -131,6 +131,7 @@ export default {
       e.preventDefault();
       if (this.searchTermsModel) {
         this.$emit('onSearchFormSubmit', { query: { q: this.searchTermsModel }, shouldNavigate: true });
+        document.getElementById('searchInput').blur();
```
Comment (brenoferreira) [inline src/components/SearchGridFormOriginal.vue]: The use of `document.getElementById` is discouraged on VueJS. Can you use this instead? https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

Comment (krysal) [reply src/components/SearchGridFormOriginal.vue]: Ok, I got it.
