### PR TITLE
Fixed excessive spacing between license icons.

### LINKED ISSUE #772: Excessive spacing between license icons
## Describe the bug

License icons are excessively spaced now that #723 has been merged, see attached pictures.

## To Reproduce

1. Go to https://ccsearch-dev.creativecommons.org/
2. Search for something
3. See error when hovering on an image
4. Click on image to see image details
5. See error under the Attribution tab
6. Click on the Info tab
7. See error again

## Screenshots

s-i1
s-i2
s-i3

## Desktop (please complete the following information)
 - OS: Win 10 Pro 1809
 - Browser: Firefox Dev. Ed. 74.0

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #772 

li

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

File: src/components/LicenseIcons.vue [hunk 1]
```diff
@@ -68,7 +68,7 @@ export default LicenseIcons;
 
   .photo-license-icon {
     height: inherit;
-    margin-right: .5rem;
+    margin-right: .1rem;
```
Comment (brenoferreira) [inline src/components/LicenseIcons.vue]: According to [the designs](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A335), I think a margin of `.3rem` is more accurate

Comment (abhisheknaiidu) [reply src/components/LicenseIcons.vue]: @brenoferreira Done :)
