### PR TITLE
Nuxt Migration

### LINKED ISSUE #940: Server rendering renders initial state and application scripts twice
## Describe the bug
When loading any page rendered by Vue Server Side rendering you can find scripts and initial state for hydration rendered twice.

## To Reproduce
1. Go to any CC Search page rendered server side
2. Open up your browser's development tools and inspect DOM nodes
3. See how application scripts and state are duplicated when rendered from server side

## Expected behavior
It would be better to render them just once to save some KBs when transferring them to the client.

## Screenshots
Captura de pantalla 2020-05-14 a las 14 15 32

## Desktop
 - Applicable to all desktop devices

## Smartphone
- Applicable to all smartphones

## Additional context
https://github.com/creativecommons/cccatalog-frontend/blob/dec2433a0f9360227c3ba2d9f429053ce1f473ac/index-server.html#L26-L28
The HTML comment placeholder is already injecting those scripts and state, while the template is calling `renderState` and `renderScripts` at the same time.

It will not reduce much from the HTML transference (a few KBs in my local tests), but will parse and download JS files just once.

I would like to open a pull request addressing those changes if you think that this is important enough to be solved. Thank you!

### LINKED ISSUE #1108: Migrate to Nuxt.js
_Immediately following this line is an assessment of Nuxt, which concludes that we should migrate cc search. Below that analysis is the original message outlining the issue._

# SSR Considerations (Migrating to Nuxt.js)

Our current SSR implementation works well, and follows the [official Vue.js SSR Guide](https://duckduckgo.com/?t=ffab&q=vue+ssr&ia=web), but it does have a few issues.

1. The site's JavaScript bundle is sent twice. Any attempt to dedupe the bundle breaks one or more components in the `/search` page component tree. This effectively **doubles** the page load of the site.
2. We lack an easy way to mark a component as client-rendering _only_. We currently have to solve for this with several checks of `typeof window !== undefined` littered through our components.
3. We have the overhead of maintaining a custom Webpack configuration and build pipeline. Webpack is notorious for frequent major version releases that break the plugin ecosystem and configuration files, so we always end up being a version behind.
4. The complexity of maintaining our own configuration complicates the implementation of more complex features—things like code-splitting per-route, or generating some pages statically and others dynamically.

For an organization of our size, I think the maintenance burden alone of maintaining the Webpack configuration is unsustainable. This is where Nuxt.js comes in.

## What is Nuxt?

Nuxt.js is a meta framework for Vue.js that handles some generic application logic. It doesn't generate any UI or MVC code (so it's not like a Django, Rails, or Laravel), but merely simplifies routing and data fetching at the page level. Some key features of Nuxt relevant to this project are:

- Automatic Code Splitting
- Server-Side Rendering
- Powerful Routing System with Asynchronous Data
- Static File Serving
- ES2015+ Transpilation
- Bundling and minifying of your JS & CSS
- Managing <head> element (<title>, <meta>, etc.)
- Hot module replacement in Development
- Pre-processor: Sass, Less, Stylus, etc.
- HTTP/2 push headers ready
- Extending with Modular architecture

In essence, Nuxt is a community-standardized and actively-developed version of our existing impementation, with improved functionality.

## A note on abstractions

Although Nuxt is quite popular and the de-facto framework of its kind for Vue, the cognitive overhead of adding a new library to CC Search should be taken seriously. In the case of Nuxt, the benefits of its addition outweigh the cons. We can reduce overall lines of code; enable new performance-improving functionality; and fix all existing SSR bugs, with a relatively quick and straightforward implementation.

## Next steps

We should schedule the Nuxt migration over the course of **two sprints**. This will allow us to complete the work with relative speed but also make product and user-facing improvements in tandem. A draft PR (#1172) has been created to track the progress of this migration.

---

*Original post:*

## Problem

The current SSR implementation sends a duplicated JavaScript bundle. We're sending ~700kb (unminified) of JavaScript to be downloaded and parsed, which is a huge burden to our users.

The error we're getting when _fixing_ the duplicated bundle is a vague client-side issue that has proven difficult to diagnose: `Cannot add children to a Comment`.

## Description

We should explore and write an RFC for switching to [Nuxt.js](https://nuxtjs.org/), a so-called _meta framework_ for Vue.js that handles application bundling, routing, SSR, and many other features. The [vue ssr docs](https://ssr.vuejs.org/#about-this-guide) recommend Nuxt as a valid alternative. I would only want to move forward with Nuxt if it adds minimal overhead/concepts and fixes current problems.

## Implementation

- [x] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #1108 by @zackkrida 
Fixes #940 by @jesusbotella
Related to #1020

## Description

Migrates cc search to [Nuxt.js](https://nuxtjs.org/), removing the need for a custom node server, webpack configuration, and build process. Doing so removes around 4,800 lines of code, decreases the average page size (excluding search result image data) from ~900kb to ~300kb, and perhaps most importantly significantly reduces complexity in the maintenance of the repository. 

## Technical details

Data loading across the site has been re-worked to add consistency and stability. Nuxt's isomorphic `fetch()` method on vue component instances simplifies data fetching on server vs. client pages significantly.

### Bugs Resolved

This PR fixes a number of visual and behavioral bugs with the current site. These fixes were the result of two major factors: A need to refactor code for nuxt's data fetching apis, and a feeling that since this PR touched so many files _already_, noticed bugs were worth fixing. This list contains descriptions of the bugs; if it's in this list, it's _no longer_ happening:

- Tripled pageviews in GA on server-rendered pages.
- Logo flickering on every route change
- Single result image flashes broken image icon on initial load + return results when visited from search results page
- When visiting a results url directly (example: https://search.creativecommons.org/search?q=ponies), images show a spinner, instead of loading server-side
- Extra whitespace between the footer and main content area
- Extra padding under donation banner on single + search results
- Filter Expansion A/B test still running (now set to expanded by default)
- Related images "pop-in" (related images used to replace old ones one-by-one, now clears + shows loading indicator)
- Flash of entire related image section on server-rendered page loads
- Interior header search bar not working

## Screenshots / Demo Links

- Demo site hosted on vercel: https://ccnuxt.zack.cat
    - Some differences here compared to prod...no microcaching of pages, different gzip/brotli minification config, etc. Should still be comparable results—if anything, our hardware is _faster_.

> Before (simple perf comparison)

before-lighthouse
before

> After

after-lighthouse
after

## Nuxt JS Migration Steps Followed

- [x] Loosely follow this migration guide: https://medium.com/@nicogranja19/how-to-migrate-a-vuejs-project-to-nuxtjs-in-7-steps-b340faf2977b
- [x] Move initial state setting and data fetching to Nuxt's `asyncData` method (see: https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)
- [x] Move all `store` files into root `store` directory (see: https://nuxtjs.org/guide/vuex-store)
  - [ ] Rewrite store files to simpler api (see: https://nuxtjs.org/guide/vuex-store#modules-mode) [not yet, due to no namespacing]
- [x] Rename page files so filename reflects route path (see: https://nuxtjs.org/guide/routing)
- [x] Migrate existing separate `index.html` and `server-index.html` pages into single `app.html` file (see: https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)
- [x] Move header, footer, modals into shared layout (https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action)
- [x] Manually test and fix every single component in the project (feasible given the current project size) 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: src/components/Filters/FilterChecklist.vue [hunk 1]
```diff
@@ -35,29 +35,36 @@
...
+            class="filter-checkbox margin-right-small"
             :checked="item.checked"
             :disabled="block(item)"
             @change="onValueChange"
           />
-          <license-icons v-if="filterType == 'licenses'" :license="item.code" />
-          {{ $t(item.name) }}
+          <LicenseIcons v-if="filterType == 'licenses'" :license="item.code" />
+          <template
+            v-if="filterType == 'providers' || filterType == 'searchBy'"
```
Comment (manniL) [inline src/components/Filters/FilterChecklist.vue:48]:
```suggestion
            v-if="['providers', 'searchBy'].includes(filterType)"
```

File: src/components/ImageDetails/ImageInfo.vue [hunk 2]
```diff
@@ -33,18 +35,21 @@
...
+      <PhotoTags :tags="image.tags" :show-header="false" />
     </div>
   </section>
 </template>
 
 <script>
-import PhotoTags from '@/components/PhotoTags'
-import getProviderName from '@/utils/getProviderName'
-import getProviderLogo from '@/utils/getProviderLogo'
+import PhotoTags from '../PhotoTags'
```
Comment (manniL) [inline src/components/ImageDetails/ImageInfo.vue:44]:
```suggestion
import PhotoTags from '~/components/PhotoTags'
```

File: src/components/SearchGridCell.vue [hunk 3]
```diff
@@ -38,10 +38,10 @@
 </template>
 
 <script>
-import LicenseIcons from '@/components/LicenseIcons'
-import getProviderLogo from '@/utils/getProviderLogo'
+import LicenseIcons from './LicenseIcons'
```
Comment (manniL) [inline src/components/SearchGridCell.vue:41]:
```suggestion
import LicenseIcons from '~/components/LicenseIcons'
```

File: src/layouts/with-nav-search.vue [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+    <HeaderSection :show-nav-search="true" />
+    <main role="main">
+      <Nuxt />
+    </main>
+    <FooterSection />
+  </div>
+</template>
+
+<style lang="scss">
+@import '~/styles/global.scss';
```
Comment (manniL) [inline src/layouts/with-nav-search.vue:12]: Might be better to import via `css` in `nuxt.config.js`

File: src/pages/about.vue [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+            <template v-slot:terms>
+              <a
+                :aria-label="$t('about.aria.terms')"
+                href="https://creativecommons.org/terms/"
+                >{{ $t('about.declaration.terms') }}</a
+              >
+            </template>
+          </i18n>
+          <i18n path="about.old-cc-search" tag="p">
+            <template v-slot:link>
```
Comment (manniL) [inline src/pages/about.vue:86]: If wanted, you could use the shorthand for `v-slot:` which is `#`
```suggestion
            <template #link>
```

File: src/store-modules/attribution-store.js [hunk 6]
```diff
@@ -1,15 +1,15 @@
-import { CopyAttribution, EmbedAttribution } from '@/analytics/events'
+import { CopyAttribution, EmbedAttribution } from '../analytics/events'
```
Comment (manniL) [inline src/store-modules/attribution-store.js:1]:
```suggestion
import { CopyAttribution, EmbedAttribution } from '~/analytics/events'
```

File: src/store-modules/social-store.js [hunk 7]
```diff
@@ -1,11 +1,11 @@
-import { SocialMediaShare } from '@/analytics/events'
+import { SocialMediaShare } from '../analytics/events'
```
Comment (manniL) [inline src/store-modules/social-store.js:1]:
```suggestion
import { SocialMediaShare } from '~/analytics/events'
```

File: CODEBASE.md [hunk 8]
```diff
@@ -4,84 +4,28 @@ This document will give you a high level overview of the modules and components
...
-
-- BrowsePage
-- CollectionsBrowsePage
-
-The reason for that is that for some time we used a [JS library](https://www.npmjs.com/package/vue-masonry) to render the image grid. This library used browser specific APIs to render the image grid. Therefore it didn't work on the server renderer. So we had to split those pages into two different versions, one that didn't render the image grid (for the server) and another that did render it (for the client). There is however a [ticket](https://github.com/creativecommons/cccatalog-frontend/issues/934) related to removing this legacy complexity.
-
-For this reason we need to be careful about using client specific APIs (such as `window`, `document`, etc.). If those are necessary, it can only run _only_ on the client side, otherwise it will break on the server and the user will end up seeing an error message when loading the page.
+- environment variables are set in the `export const env = {}` object. Varibles are set with camel case names like this `process.env.varNameGoesHere` and their default values are formatted in the more conventional `process.env.VAR_NAME_GOES_HERE` format.
```
Comment (manniL) [inline CODEBASE.md:29]: Instead of relying on `env`, you might want to use the new [`runtimeConfig`](https://nuxtjs.org/guide/runtime-config/) feature as well.

Comment (zackkrida) [reply CODEBASE.md:29]: I'd like to, but there's some places in the original codebase where access to environment variables is needed, but `$config` isn't avaliable. After some refactoring we'll switch to `runtimeConfig`.

Comment (manniL) [reply CODEBASE.md:29]: You can set the variables for both, `env` and `publicRuntimeConfig`. Then you can use `process.env.XYZ` whereever needed and migrate the rest to `$config`. Downside of `process.env` is that a rebuild is needed to change the values (while it's not when using `$config`).

File: src/pages/index.vue [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+  <HeroSection />
+</template>
+
+<script>
+import { CLEAR_FILTERS } from '~/store-modules/mutation-types'
+
+const HomePage = {
+  name: 'home-page',
+  fetch() {
+    this.$store.commit(CLEAR_FILTERS)
```
Comment (manniL) [inline src/pages/index.vue:11]: Instead of using `fetch` here, `beforeMount` would suffice too. Mostly because there is no API logic involved and `fetchOnServer` is disabled anyway.

**Review by akmadian — COMMENTED** [review]
Looks good to me! I'm not sure if there's ongoing discussion re @manniL's suggestions, but I'd second them.

**Review by mathemancer — APPROVED** [review]
Seems to be working, and the tests are passing for me.

The only observed "problem" (a bit of a stretch; I only mention it for completeness) I found is that on the new version, the images' places are held in the results page by off-color square boxes before (and as) they are loaded.  As the different images load at different widths, these boxes jump around a bit on the page accordingly.  In the previous version, it seems that either these boxes didn't exist, or they were transparent.

**Review by aldenstpage — APPROVED** [review]

**Comment by zackkrida** [comment]
@manniL Thank you for your review of this PR and your guidance! This Nuxt migration PR has been merged into our development branch, which means it will enter production in the next week or so.

We'll write a blog post soon about the migration and our thoughts on Nuxt.js (tldr; Nuxt is great, saves us a ton of time, reduced boilerplate, improved perf, etc.) and keep you posted. Thanks again!
