### PR TITLE
fixed count for image results >10K #540

### LINKED ISSUE #540: Fix image count when result set is over 10K images
There's been a change to the CC Catalog API in which a search query result set over 10.000 images will have a capped `result_count` of `10000`, when in reality there's more than 10.000 images in the catalog.  For example: https://api.creativecommons.engineering/image/search?q=cat

Screen Shot 2019-12-04 at 10 44 24

We need to change the display of the image count in the UI, which now tells users that there are exactly 10.000 images, to something like `Over 10.000 images` or `More than 10.000 images` or `10.000+ images`.

### PR DESCRIPTION
**Pull request by madewithkode**
### Fixes #540

The CC Catalog API has a capped result count of 10,000 even when results exceed this amount. This fix is aimed at helping users understand this by reflecting it on the UI search results count whenever that is the case.

Screenshot from 2019-12-20 23-01-39
Screenshot showing updated change to search results count when >10K results

Screenshot from 2019-12-20 23-02-43
Screenshot showing original search result count when <10K results

---

Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kgodey** [comment]
@madewithkode FYI, Creative Commons is going on winter break so you likely won't see a response to this PR until the week of Jan 6.

**Comment by madewithkode** [comment]
Oh. Quite a while, No issues.
Happy Holidays :)

File: src/components/SearchGridManualLoad.vue [hunk 1]
```diff
@@ -94,7 +94,8 @@ export default {
     },
     _imagesCount() {
       const count = this.useInfiniteScroll ? this.$store.state.imagesCount : this.imagesCount;
-      return count.toLocaleString('en');
+      const localeCount = count.toLocaleString('en');
+      return localeCount === '10,000' ? `Over ${localeCount} images` : `${localeCount} images`;
```
Comment (brenoferreira) [inline src/components/SearchGridManualLoad.vue]: Doing number checking instead of string checking is better in this case. It's faster, and it prevents future problems in case the number changes for any reason. Can you change the check to `count >= 10000`?

**Comment by madewithkode** [comment]
Alright, Let me figure that.

File: src/components/SearchGridManualLoad.vue (hunk 1 above)
Comment (madewithkode) [reply src/components/SearchGridManualLoad.vue]: Fixed now!
